#!/bin/bash

for base in ~/lanterne ~/lanterne/pages; do
    cd $base
    for dir in [0-9]*; do
	echo $dir
	if [ ! -d small/$dir ]; then
	    mkdir small/$dir
	    for image in $dir/*.jpg; do
		convert -resize 50% $image small/$image
	    done
	fi
	if [ ! -d tiny/$dir ]; then
	    mkdir tiny/$dir
	    for image in $dir/*.jpg; do
		convert -resize 10% $image tiny/$image
	    done
	fi
    done
done
